### ISSUE TITLE
[BUG] Error when use function readTags,readTagsAsMap,readArtwork

### ISSUE THREAD

**Issue by zgramming** [Samurai016/Audiotagger#12]
# Example 

```
class WelcomeScreen extends StatefulWidget {
  @override
  _WelcomeScreenState createState() => _WelcomeScreenState();
}

class _WelcomeScreenState extends State<WelcomeScreen> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            icon: Icon(Icons.ac_unit_outlined),
            onPressed: () async {
              try {
                final grantedPermissionStorage = await Permission.storage.status;
                print(grantedPermissionStorage);
                if (grantedPermissionStorage != PermissionStatus.granted) {
                  await Permission.storage.request();
                } else {
                  final tagger = Audiotagger();
                  final dir = Directory('/storage/emulated/0/');
                  final mp3Path = dir.toString();
                  List<FileSystemEntity> _songs = [];
                  final files = dir.listSync(recursive: true, followLinks: false);
                  // print(files);
                  for (var file in files) {
                    if (file.path.endsWith('.mp3')) {
                      final path = file.path;
                      final map = await tagger.readTags(path: path);
                    }
                  }
                }
              } catch (e) {
                GlobalFunction.showSnackBar(
                  context,
                  content: Text(e.toString()),
                  snackBarType: SnackBarType.error,
                );
              }
            },
          ),
        ],
      ),
      
    );
  }
}

```

My flow is : 

- Check permission storage 
- If granted , i want get all mp3 file in `/storage/emulated/0/`
- Then get Tags file using function **readTags**

# Expectation 

Show Tags file if return **readTags** is not null otherwise ignore it.

# Result 

The function throwing error : 
```
W/System.err(11993): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jaudiotagger.tag.Tag.getFirst(org.jaudiotagger.tag.FieldKey)' on a null object reference
W/System.err(11993): 	at com.nicolorebaioli.audiotagger.AudiotaggerPlugin.readTags(AudiotaggerPlugin.java:181)
W/System.err(11993): 	at com.nicolorebaioli.audiotagger.AudiotaggerPlugin.onMethodCall(AudiotaggerPlugin.java:70)
W/System.err(11993): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(11993): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(11993): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/System.err(11993): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11993): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(11993): 	at android.os.Looper.loop(Looper.java:165)
W/System.err(11993): 	at android.app.ActivityThread.main(ActivityThread.java:6729)
W/System.err(11993): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11993): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(11993): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

```

I'm speculating this line is making the [error](https://github.com/Samurai016/Audiotagger/blob/0c2502e0f4729f2a29cfecdf0ba32521d40fbc08/android/src/main/java/com/nicolorebaioli/audiotagger/AudiotaggerPlugin.java#L173).

**Comment by Samurai016** [comment]
Thank you so much @zgramming ,
I updated the package and fixed the bug.
I just released the [2.1.0](https://github.com/Samurai016/Audiotagger/releases/tag/2.1.0) version on [pub.dev](https://pub.dev/packages/audiotagger).
