### ISSUE TITLE
Error writing to m4a format file

### ISSUE THREAD

**Issue by mrdong916** [Samurai016/Audiotagger#17]
```
E/generic: File /storage/emulated/0/五音音乐/姚六一 - 雾里.m4a being read
    org.jaudiotagger.audio.exceptions.NullBoxIdException: Unable to find next atom because identifier is invalid ��������
        at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.update(Mp4BoxHeader.java:153)
        at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.seekWithinLevel(Mp4BoxHeader.java:273)
        at org.jaudiotagger.audio.mp4.Mp4InfoReader.read(Mp4InfoReader.java:95)
        at org.jaudiotagger.audio.mp4.Mp4FileReader.getEncodingInfo(Mp4FileReader.java:41)
        at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:107)
        at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:356)
        at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:193)
        at com.nicolorebaioli.audiotagger.AudiotaggerPlugin.writeTags(AudiotaggerPlugin.java:117)
        at com.nicolorebaioli.audiotagger.AudiotaggerPlugin.onMethodCall(AudiotaggerPlugin.java:87)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:822)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
I recently updated the latest version of this issue, and I had no problems writing back in the early days

**Comment by adem74** [comment]
@mrdong916  hello, could you find a solution?

**Comment by Samurai016** [comment]
Hi @mrdong916 , sorry for the delay.
Could you send me the .m4a file please?
Thank you

**Comment by mrdong916** [comment]
> Hi @mrdong916 , sorry for the delay.
> Could you send me the .m4a file please?
> Thank you

https://ws28.cn/f/5v1gxyk53og

**Comment by Samurai016** [comment]
I think it is a duplicate of issue #7.
I tried with other .m4a files and it works.
I found this issue on the original jaudiotagger repo which charge the YouTube downloaded file of this problem (as for the mp3 files, they seems to not be well formed).

As I answered in that issue I tried converting the file using ffmpeg and after that it works.
The problem is with the specified file.
I used this command
```bash
ffmpeg -i "姚六一 - 雾里-1.m4a" -c:a aac -vn "姚六一 - 雾里-1-changed.m4a"
```

**Comment by shadow5688** [comment]
@Samurai016 Is it possible to provide tag editing for other audio formats too? I do get your point that we can use FFmpeg to convert audio to mp3 and then edit the tags. But, it's not a proper solution, just a workaround to the problem. Also, If you have used FFmpeg, then you might be familiar with the increase in app size. So using FFmpeg to convert audio, just coz I want to edit tags isn't the best approach. Instead, I would prefer not to edit tags at all.
So, I would like to request you to add an option to edit tags for other formats too, which aren't mp3.

**Comment by markst** [comment]
Are `.m4a` files supported?
```
W/System.err( 4854): org.jaudiotagger.audio.exceptions.CannotReadException: This file does not appear to be an Mp4  file
```
